package modulo;
// Generated 28 nov 2022 19:53:05 by Hibernate Tools 6.1.3.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Clase generated by hbm2java
 */
public class Clase implements java.io.Serializable {

	private Short codigo;
	private String nombre;
	private BigDecimal consumoMinimoAnual;
	private short porcentajeAdicional;
	private Set viajeros = new HashSet(0);

	public Clase() {
	}

	public Clase(String nombre, BigDecimal consumoMinimoAnual, short porcentajeAdicional) {
		this.nombre = nombre;
		this.consumoMinimoAnual = consumoMinimoAnual;
		this.porcentajeAdicional = porcentajeAdicional;
	}

	public Clase(String nombre, BigDecimal consumoMinimoAnual, short porcentajeAdicional, Set viajeros) {
		this.nombre = nombre;
		this.consumoMinimoAnual = consumoMinimoAnual;
		this.porcentajeAdicional = porcentajeAdicional;
		this.viajeros = viajeros;
	}

	public Short getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Short codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public BigDecimal getConsumoMinimoAnual() {
		return this.consumoMinimoAnual;
	}

	public void setConsumoMinimoAnual(BigDecimal consumoMinimoAnual) {
		this.consumoMinimoAnual = consumoMinimoAnual;
	}

	public short getPorcentajeAdicional() {
		return this.porcentajeAdicional;
	}

	public void setPorcentajeAdicional(short porcentajeAdicional) {
		this.porcentajeAdicional = porcentajeAdicional;
	}

	public Set getViajeros() {
		return this.viajeros;
	}

	public void setViajeros(Set viajeros) {
		this.viajeros = viajeros;
	}


	public String toString() {
		return "Clase [codigo=" + codigo + ", nombre=" + nombre + ", consumoMinimoAnual=" + consumoMinimoAnual
				+ ", porcentajeAdicional=" + porcentajeAdicional + "]";
	}

	
	
}
