package modulo;
// Generated 28 nov 2022 19:53:05 by Hibernate Tools 6.1.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Estacion generated by hbm2java
 */
public class Estacion implements java.io.Serializable {

	private Short codigo;
	private String nombre;
	private String ubicacion;
	private short agnoInauguracion;
	private short vias;
	private Set billetesForCodigoEstacionDestino = new HashSet(0);
	private Set billetesForCodigoEstacionOrigen = new HashSet(0);

	public Estacion() {
	}

	public Estacion(String nombre, String ubicacion, short agnoInauguracion, short vias) {
		this.nombre = nombre;
		this.ubicacion = ubicacion;
		this.agnoInauguracion = agnoInauguracion;
		this.vias = vias;
	}

	public Estacion(String nombre, String ubicacion, short agnoInauguracion, short vias,
			Set billetesForCodigoEstacionDestino, Set billetesForCodigoEstacionOrigen) {
		this.nombre = nombre;
		this.ubicacion = ubicacion;
		this.agnoInauguracion = agnoInauguracion;
		this.vias = vias;
		this.billetesForCodigoEstacionDestino = billetesForCodigoEstacionDestino;
		this.billetesForCodigoEstacionOrigen = billetesForCodigoEstacionOrigen;
	}

	public Short getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Short codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	public short getAgnoInauguracion() {
		return this.agnoInauguracion;
	}

	public void setAgnoInauguracion(short agnoInauguracion) {
		this.agnoInauguracion = agnoInauguracion;
	}

	public short getVias() {
		return this.vias;
	}

	public void setVias(short vias) {
		this.vias = vias;
	}

	public Set getBilletesForCodigoEstacionDestino() {
		return this.billetesForCodigoEstacionDestino;
	}

	public void setBilletesForCodigoEstacionDestino(Set billetesForCodigoEstacionDestino) {
		this.billetesForCodigoEstacionDestino = billetesForCodigoEstacionDestino;
	}

	public Set getBilletesForCodigoEstacionOrigen() {
		return this.billetesForCodigoEstacionOrigen;
	}

	public void setBilletesForCodigoEstacionOrigen(Set billetesForCodigoEstacionOrigen) {
		this.billetesForCodigoEstacionOrigen = billetesForCodigoEstacionOrigen;
	}


	public String toString() {
		return "Estacion [codigo=" + codigo + ", nombre=" + nombre + ", ubicacion=" + ubicacion + ", agnoInauguracion="
				+ agnoInauguracion + ", vias=" + vias + "]";
	}
	

}
