package modulo;
// Generated 28 nov 2022 19:53:05 by Hibernate Tools 6.1.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Viajero generated by hbm2java
 */
public class Viajero implements java.io.Serializable {

	private Short codigo;
	private Clase clase;
	private String nombre;
	private String fechaNacimiento;
	private String lugarResidencia;
	private String correo;
	private short puntos;
	private Set billetes = new HashSet(0);

	public Viajero() {
	}

	public Viajero(Clase clase, String nombre, String fechaNacimiento, String lugarResidencia, String correo,
			short puntos) {
		this.clase = clase;
		this.nombre = nombre;
		this.fechaNacimiento = fechaNacimiento;
		this.lugarResidencia = lugarResidencia;
		this.correo = correo;
		this.puntos = puntos;
	}

	public Viajero(Clase clase, String nombre, String fechaNacimiento, String lugarResidencia, String correo,
			short puntos, Set billetes) {
		this.clase = clase;
		this.nombre = nombre;
		this.fechaNacimiento = fechaNacimiento;
		this.lugarResidencia = lugarResidencia;
		this.correo = correo;
		this.puntos = puntos;
		this.billetes = billetes;
	}

	public Short getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Short codigo) {
		this.codigo = codigo;
	}

	public Clase getClase() {
		return this.clase;
	}

	public void setClase(Clase clase) {
		this.clase = clase;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(String fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public String getLugarResidencia() {
		return this.lugarResidencia;
	}

	public void setLugarResidencia(String lugarResidencia) {
		this.lugarResidencia = lugarResidencia;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public short getPuntos() {
		return this.puntos;
	}

	public void setPuntos(short puntos) {
		this.puntos = puntos;
	}

	public Set getBilletes() {
		return this.billetes;
	}

	public void setBilletes(Set billetes) {
		this.billetes = billetes;
	}

	public String toString() {
		return "Viajero [codigo=" + codigo + ", clase=" + clase + ", nombre=" + nombre + ", fechaNacimiento="
				+ fechaNacimiento + ", lugarResidencia=" + lugarResidencia + ", correo=" + correo + ", puntos=" + puntos
				+ "]";
	}

	
}
